#!/usr/bin/env python3
"""
Generate route shells from index.html so /about, /play and unknown URLs load
directly on ANY static host (no rewrite rules required), plus a tiny redirect
page for retired URLs (/work → /#work).

    python3 tools/build_routes.py

Run it again whenever you edit <head> in index.html. index.html is the source
of truth; the generated files are copies with page-specific title/description.

Paths are RELATIVE, so the site works from a domain root (localhost, a custom
domain) and from a sub-folder (GitHub Pages: https://<user>.github.io/<repo>/):
  • index.html          sits at the site root      → 'assets/…'
  • about/, play/, work/ are one folder deeper      → '../assets/…'
  • 404.html is served by GitHub Pages for a missing URL at ANY depth, so it
    can't know its depth ahead of time: a tiny inline script works out the
    site folder and sets <base> before any asset is requested.
"""
import os, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = open(os.path.join(ROOT, "index.html"), encoding="utf-8").read()
MARK = "<!-- GENERATED by tools/build_routes.py from index.html — do not edit directly -->"

PAGES = {
    "about/index.html": ("About — Sayf Elkousy", "Houston-born, Egyptian American, fluent in Arabic. The story so far."),
    "play/index.html":  ("Play — Sayf Elkousy",  "Soccer, travel, friends — life away from the screen."),
    "404.html":         ("Lost — Sayf Elkousy",  "Page not found."),
}

# Retired URLs → where they live now (a hash on the site root). These pages load
# no app code; they compute the site folder from their own URL and replace
# themselves. The client router applies the same map in-app (data/site.js).
REDIRECTS = {
    "work/index.html": "#work",
}

REDIRECT_PAGE = """<!doctype html>
<!-- GENERATED by tools/build_routes.py — do not edit directly -->
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>Sayf Elkousy</title>
  <meta name="robots" content="noindex" />
  <meta http-equiv="refresh" content="0; url=../{to}" />
  <script>
    // <site>/work, <site>/work/ or <site>/work/index.html → <site>/{to}
    location.replace(location.pathname.replace(/[^/]+\\/?(index\\.html)?$/, "") + "{to}");
  </script>
</head>
<body style="background:#030507;color:#f1f4f6;font-family:ui-monospace,monospace">
  <p>Moved to <a href="../{to}" style="color:#6b93ff">the Work section</a>.</p>
</body>
</html>
"""

# For 404.html: its depth is unknown (GitHub Pages serves it for a missing URL
# anywhere in the site), so its assets can't be written as fixed paths. Instead
# they're added by this script once it has found the site folder: it checks
# whether the site's own files exist under /<first-segment>/ (a GitHub Pages
# project site) and otherwise uses '/' (a domain root). A <base> then makes
# every relative URL on the page — assets and links — resolve from there.
BOOT_SCRIPT = """<script>
    (function () {
      var ASSETS = %s;
      var seg = location.pathname.split("/").filter(Boolean)[0];
      var tries = (seg ? ["/" + seg + "/"] : []).concat(["/"]);
      (function next(i) {
        if (i >= tries.length) return;
        fetch(tries[i] + "assets/js/core/base.js", { method: "HEAD", cache: "no-store" })
          .then(function (r) { if (!r.ok) throw 0; boot(tries[i]); })
          .catch(function () { next(i + 1); });
      })(0);
      function boot(root) {
        var base = document.createElement("base");
        base.href = root;
        document.head.insertBefore(base, document.head.firstChild);
        ASSETS.forEach(function (a) {
          var el = document.createElement(a[0] === "script" ? "script" : "link");
          if (a[0] === "script") { el.type = "module"; el.src = a[1]; }
          else { el.rel = a[0]; el.href = a[1]; if (a[0] === "icon") el.type = "image/svg+xml"; }
          document.head.appendChild(el);
        });
      }
    })();
  </script>"""

REL = re.compile(r'((?:href|src)=")(?![a-z][a-z0-9+.-]*:|/|#)', re.I)  # relative URLs only


def write(rel, html):
    out = os.path.join(ROOT, rel)
    os.makedirs(os.path.dirname(out) or ROOT, exist_ok=True)
    open(out, "w", encoding="utf-8").write(html)
    print("wrote", rel)


for rel, (title, desc) in PAGES.items():
    html = re.sub(r"<title>.*?</title>", f"<title>{title}</title>", SRC, count=1)
    html = re.sub(r'(<meta name="description" content=")[^"]*(")', rf"\g<1>{desc}\g<2>", html, count=1)
    if rel == "404.html":
        assets = []
        def take(m):
            kind, url = m.group(1) or "script", m.group(2) or m.group(3)
            assets.append([kind, url])
            return ""
        # pull out every relative asset tag (icon, stylesheets, module); the boot script adds them back
        html = re.sub(r'[ \t]*(?:<link rel="(icon|stylesheet)" href="(?![a-z]+:)([^"]+)"[^>]*/>|<script type="module" src="([^"]+)"></script>)\n', take, html)
        import json
        html = html.replace('<meta charset="utf-8" />', '<meta charset="utf-8" />\n  ' + BOOT_SCRIPT % json.dumps(assets), 1)
    else:
        depth = rel.count("/")
        html = REL.sub(lambda m: m.group(1) + "../" * depth, html)
    html = html.replace("<!doctype html>", "<!doctype html>\n" + MARK, 1)
    write(rel, html)

for rel, to in REDIRECTS.items():
    write(rel, REDIRECT_PAGE.replace("{to}", to))
