#!/usr/bin/env python3
"""
Generate route shells from index.html so /about, /play and unknown URLs load
directly on ANY static host (no rewrite rules required), plus a tiny redirect
page for retired URLs (/work → /#work).

    python3 tools/build_routes.py

Run it again whenever you edit <head> in index.html. index.html is the source
of truth; the generated files are copies with page-specific title/description.
"""
import os, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = open(os.path.join(ROOT, "index.html"), encoding="utf-8").read()

PAGES = {
    "about/index.html": ("About — Sayf Elkousy", "Houston-born, Egyptian American, fluent in Arabic. The story so far."),
    "play/index.html":  ("Play — Sayf Elkousy",  "Soccer, travel, friends — life away from the screen."),
    "404.html":         ("Lost — Sayf Elkousy",  "Page not found."),
}

# Retired URLs. Work is now a section of Home. These pages load no app code:
# they replace themselves with the new address (keeping old bookmarks alive).
# The client router applies the same map to in-app navigation (data/site.js).
REDIRECTS = {
    "work/index.html": "/#work",
}

REDIRECT_PAGE = """<!doctype html>
<!-- GENERATED by tools/build_routes.py — do not edit directly -->
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>Sayf Elkousy</title>
  <meta name="robots" content="noindex" />
  <link rel="canonical" href="{to}" />
  <meta http-equiv="refresh" content="0; url={to}" />
  <script>location.replace("{to}");</script>
</head>
<body style="background:#030507;color:#f1f4f6;font-family:ui-monospace,monospace">
  <p>Moved to <a href="{to}" style="color:#6b93ff">{to}</a>.</p>
</body>
</html>
"""


def write(rel, html):
    out = os.path.join(ROOT, rel)
    os.makedirs(os.path.dirname(out) or ROOT, exist_ok=True)
    open(out, "w", encoding="utf-8").write(html)
    print("wrote", rel)


for rel, (title, desc) in PAGES.items():
    html = re.sub(r"<title>.*?</title>", f"<title>{title}</title>", SRC, count=1)
    html = re.sub(r'(<meta name="description" content=")[^"]*(")', rf"\g<1>{desc}\g<2>", html, count=1)
    html = html.replace("<!doctype html>", "<!doctype html>\n<!-- GENERATED by tools/build_routes.py from index.html — do not edit directly -->", 1)
    write(rel, html)

for rel, to in REDIRECTS.items():
    write(rel, REDIRECT_PAGE.format(to=to))
